// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMVExVvMO3h0V43tujHgwGSRD21lxm1FY',
    appId: '1:959737557969:web:bb2b9f18e5fd9cf35666f0',
    messagingSenderId: '959737557969',
    projectId: 'blog-app-b3075',
    authDomain: 'blog-app-b3075.firebaseapp.com',
    storageBucket: 'blog-app-b3075.appspot.com',
    measurementId: 'G-P3RX53J075',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnf4GU_o5VNFxA4DEjnCZyBcIA8sqPKeQ',
    appId: '1:959737557969:android:7224907d2d8ae12f5666f0',
    messagingSenderId: '959737557969',
    projectId: 'blog-app-b3075',
    storageBucket: 'blog-app-b3075.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByq-Vmiuu5kp6QAcU8KsHIsxMWOdnmGK4',
    appId: '1:959737557969:ios:f1a5fb6ead9bfee65666f0',
    messagingSenderId: '959737557969',
    projectId: 'blog-app-b3075',
    storageBucket: 'blog-app-b3075.appspot.com',
    iosBundleId: 'com.example.cleanArchitectureTdd',
  );
}
